// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maxpyehrsnrcfriukuvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1heHB5ZWhyc25yY2ZyaXVrdXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTMxNzAsImV4cCI6MjA3MDE4OTE3MH0.zpnOIhq8O115WTh2keIkXP9fI1zyRA8lg_5EUAcIIAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});